### ISSUE TITLE
Markdown not correctly parsed when part of include

### ISSUE THREAD

**Issue by simplyeffectiveweb** [treygriffith/metalsmith-include#4]
I just realisd the reason the markdown was not parsing correctly.

It's when I use Include. I missed it initially because '**' (for strong) works, but for example '##' for headers does not.

Simply taking out the Include command enables markdown to parse correctly.

Also, in the overview, it is not clear what 'thanks.jade' is. Obvioulsy a template, but in the example you don't show what is inside this, nor how that would work (the overview suggests a unique template for each include, which presume is not the case). I mention this only in case it is somehow related.

**Comment by madeofpeople** [comment]
I have the same issue above, I can parse out the content with custom markdown filters but converting markdown to html, to then have to convert certain keys is problematic. The example in the docs implies that ####Blah becomes <h4>Blah</h4> for the included .md file's contents, but that is not my experience. Any news from maintainer?

**Comment by simplyeffectiveweb** [comment]
I continued to try, particularly placing the include plugin in different positions. But withou success. Either the markdown did not parse or the plugin did not work.

If I get time I would like to look at this plugin because I think the concept has potential. However I doubt my dev skills are up to the developer of this. There are two things that really need to change tha I'm not using it really stand out.  1) is the need to include the list of files to include. This alone almost makes the process too manual to help,   2) fix the above issue.

(in fairness re. issue 1, this was not help by me using handlebars which has the same need for a list of the partials in the build file. With this and include, far too much manual change needed that almost take away the advantage of a static site generator. Definiltely not a direction any 'making a process easier' program or plugin wants to go in my opinion, and i will be switching to Swig)

**Comment by treygriffith** [comment]
Can someone write a test that illustrates the issue? I'd be happy to look into fixing it with a failing test.

**Comment by madeofpeople** [comment]
@treygriffith 
It's more of an integration testing issue and less a unit testing issue.

I will try and step through it (since this module is still the 'best solution' for the use-case).

In metalsmith.json
```
    "metalsmith-include": {},
    "metalsmith-markdown": {},
    "metalsmith-templates": {
      "engine": "swig"
    },
```

Example md file:
```
---
template: includetest.html
include:
  thanks: thanks.md
---

### Welcome to my website!
```
---
partial: true
---
thanks.md:
```
##I'm the thanks markdown file!
```

Then in my includetest.html template (we're using swig)
```
{{include.thanks}}
``

the output is 

```
## I'm the thanks markdown file!
```

instead of

```
<h2> I'm the thanks markdown file!</h2>
```

as would be expected.

Hope this clarifies.

I've had success with the following modification:
```
file[name] = marked( String( included[filename].contents ));
```
Given it's meant to work with markdown files, I think it's not expanding the scope, or adding too much complexity to the plugin.

I am happy to set up a pull-request if you're open to merging it.

This small-change would help people get their expected results, and definitely put metalsmith-include square in the center our static site workflow (right now we're abusing collections to get a similar effect).

**Comment by treygriffith** [comment]
@madeofpeople Perhaps I'm misunderstanding, but isn't this just an issue of the order of plugins?

Metalsmith runs through it's plugins in order, so as long as you run your markdown parser before metalsmith-include (which you do by calling `.use` for markdown before `.use` for metalsmith-include) it should work fine.

I don't want to assume that everything that comes through metalsmith-include is markdown, that feels too heavy handed.

**Comment by simplyeffectiveweb** [comment]
@treygriffith  appreciate the response. but the thread shows the issue (and ourselves) is beyond plugin order. I tested this a lot (including order as stated in 3rd post). The only solution I found was not using Include. 

The 'thanks.jade' in the Include instructions was not clear to me. Why this template? Perhaps this links to the issue?

Mostly, the issue was clearly not about order as the md within Include parsed '**' ok, but not other md formatting (all standard and working find as soon as Include not used).

Also, as i mentioned above, the need to manually list the files needed for Include kind of makes it difficult to use anyway. I realised that to have metalsmith as a workable package, this idea of manual file listing (Handlebar's partials and Include's files) was going against the concept (imho).

**Comment by treygriffith** [comment]
@simplyeffectiveweb I wish I could find the original repo that I pulled the example in the readme from.

However, I did find another project of mine where I'm using metalsmith-templates, metalsmith-include, and markdown parsing all together. It works fine, which is why I'm having trouble understanding this issue.

I've only used Jade, which may be part of the issue, but the way I have it laid it out is as follows:

> Every markdown file has an accompanying template declared in its frontmatter, even if that template (in jade) is like this:
```
!= contents
```

> When including files, the extension is left off, like so:
```
template: main.jade
include:
  my_included_file: my_included_file
```

> I leave off the extension so that the plugin will include `my_included_file` even if it has been transformed from `my_included_file.md` to `my_included_file.html`.

That's what works for me.

Is there anything in there that sounds significantly different from what you're trying?

**Comment by madeofpeople** [comment]
@treygriffith

Changing the plugin order results in an error since there are no markdown files being passed in since the markdown plugin converts them to html.

The error:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unknown file partials/about-ourteam.md
    at include (/Users/xxx/xxx/xxx/node_modules/metalsmith-include/index.js:54:45)
    at /Users/xxx/xxx/xxx/node_modules/metalsmith-include/node_modules/async/lib/async.js:118:13
    at Array.forEach (native)
```

**Comment by madeofpeople** [comment]
@treygriffith 
Interesting, I had not seen your comment above to simplyeffective regading dropping the extension from the filename. I didn't know about this behavior in metalsmith.

This does in fact work, and so I chalk this whole issue up to an error in documentation (given your examples specify the "thanks.md" and well that's what any of us who wanted to use this plugin tried first.

I strongly recommend updating the docs!

**Comment by treygriffith** [comment]
I updated the docs to reflect what we talked about here. I'll close this issue now - let me know if there's anything further that needs to be worked out.

Thanks for your patience!
